name: "이슈 생성"
description: "Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다."
title: "[GitHub]: "

body:
  - type: input
    id: parentKey
    attributes:
      label: "🎟️ 상위 작업 (Ticket Number)"
      description: "상위 작업의 Ticket Number를 기입해주세요."
      placeholder: "GAME-"
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: "🌳 브랜치명 (Branch)"
      description: "영어로 브랜치명을 작성해주세요."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 상세 내용(Description)"
      description: "이슈에 대해서 설명해주세요."
    validations:
      required: true
