from app.score_calculator.block.block import Block
from app.score_calculator.enums.enums import Yaku


def has_opened_blocks(blocks: list[Block]) -> bool:
    return any(block.is_opened for block in blocks)


excluded_yakus: dict[Yaku, list[Yaku]] = {
    Yaku.BigFourWinds: [
        Yaku.BigThreeWinds,
        Yaku.AllPungs,
        Yaku.PrevalentWind,
        Yaku.SeatWind,
        Yaku.PungOfTerminalsOrHonors,
    ],
    Yaku.BigThreeDragons: [Yaku.TwoDragonsPungs, Yaku.DragonPung],
    Yaku.NineGates: [Yaku.FullFlush, Yaku.ConcealedHand, Yaku.PungOfTerminalsOrHonors],
    Yaku.FourKongs: [Yaku.SingleWait],
    Yaku.SevenShiftedPairs: [Yaku.FullFlush, Yaku.ConcealedHand, Yaku.SingleWait],
    Yaku.ThirteenOrphans: [Yaku.AllFives, Yaku.ConcealedHand, Yaku.SingleWait],
    Yaku.AllTerminals: [
        Yaku.AllPungs,
        Yaku.OutsideHand,
        Yaku.PungOfTerminalsOrHonors,
        Yaku.NoHonorTiles,
    ],
    Yaku.LittleFourWinds: [
        Yaku.BigThreeWinds,
    ],  # Yaku.PungOfTerminalsOrHonors by used block flag
    Yaku.LittleThreeDragons: [Yaku.TwoDragonsPungs, Yaku.DragonPung],
    Yaku.AllHonors: [Yaku.AllPungs, Yaku.OutsideHand, Yaku.PungOfTerminalsOrHonors],
    Yaku.FourConcealedPungs: [],
    Yaku.PureTerminalChows: [
        Yaku.SevenPairs,
        Yaku.FullFlush,
        Yaku.AllChows,
        Yaku.NoHonorTiles,
        Yaku.PureDoubleChow,
        Yaku.TwoTerminalChows,
    ],
    Yaku.QuadrupleChow: [Yaku.PureShiftedPungs, Yaku.TileHog, Yaku.PureDoubleChow],
    Yaku.FourPureShiftedPungs: [Yaku.PureTripleChow, Yaku.AllPungs],
    Yaku.FourPureShiftedChows: [Yaku.ShortStraight, Yaku.TwoTerminalChows],
    Yaku.ThreeKongs: [],
    Yaku.AllTerminalsAndHonors: [
        Yaku.AllPungs,
        Yaku.OutsideHand,
        Yaku.PungOfTerminalsOrHonors,
    ],
    Yaku.SevenPairs: [Yaku.ConcealedHand, Yaku.SingleWait],
    Yaku.GreaterHonorsAndKnittedTiles: [Yaku.AllTypes, Yaku.ConcealedHand],
    Yaku.AllEvenPungs: [Yaku.AllPungs, Yaku.AllSimples],
    Yaku.FullFlush: [Yaku.NoHonorTiles],
    Yaku.PureTripleChow: [Yaku.PureShiftedPungs, Yaku.PureDoubleChow],
    Yaku.PureShiftedPungs: [Yaku.PureTripleChow],
    Yaku.UpperTiles: [Yaku.NoHonorTiles],
    Yaku.MiddleTiles: [Yaku.NoHonorTiles, Yaku.AllSimples],
    Yaku.LowerTiles: [Yaku.NoHonorTiles],
    Yaku.PureStraight: [],
    Yaku.ThreeSuitedTerminalChows: [
        Yaku.AllChows,
        Yaku.NoHonorTiles,
        Yaku.MixedDoubleChow,
        Yaku.TwoTerminalChows,
    ],
    Yaku.PureShiftedChows: [],
    Yaku.AllFives: [Yaku.AllSimples],
    Yaku.TriplePung: [],
    Yaku.ThreeConcealedPungs: [],
    Yaku.LesserHonorsAndKnittedTiles: [Yaku.AllTypes, Yaku.ConcealedHand],
    Yaku.KnittedStraight: [],
    Yaku.UpperFour: [Yaku.NoHonorTiles],
    Yaku.LowerFour: [Yaku.NoHonorTiles],
    Yaku.BigThreeWinds: [],
    Yaku.MixedStraight: [],
    Yaku.ReversibleTiles: [Yaku.OneVoidedSuit],
    Yaku.MixedTripleChow: [],
    Yaku.MixedShiftedPungs: [],
    Yaku.ChickenHand: [],
    Yaku.LastTileDraw: [Yaku.SelfDrawn],
    Yaku.LastTileClaim: [],
    Yaku.OutWithReplacementTile: [Yaku.SelfDrawn],
    Yaku.RobbingTheKong: [Yaku.LastTile],
    Yaku.TwoConcealedKongs: [],
    Yaku.AllPungs: [],
    Yaku.HalfFlush: [],
    Yaku.MixedShiftedChows: [],
    Yaku.AllTypes: [],
    Yaku.MeldedHand: [Yaku.SingleWait],
    Yaku.TwoDragonsPungs: [Yaku.DragonPung],
    Yaku.OutsideHand: [],
    Yaku.FullyConcealedHand: [],
    Yaku.TwoMeldedKongs: [],
    Yaku.LastTile: [],
    Yaku.DragonPung: [],
    Yaku.PrevalentWind: [],
    Yaku.SeatWind: [],
    Yaku.ConcealedHand: [],
    Yaku.AllChows: [],
    Yaku.TileHog: [],
    Yaku.DoublePung: [],
    Yaku.TwoConcealedPungs: [],
    Yaku.ConcealedKong: [],
    Yaku.AllSimples: [Yaku.NoHonorTiles],
    Yaku.PureDoubleChow: [],
    Yaku.MixedDoubleChow: [],
    Yaku.ShortStraight: [],
    Yaku.TwoTerminalChows: [],
    Yaku.PungOfTerminalsOrHonors: [],
    Yaku.MeldedKong: [],
    Yaku.OneVoidedSuit: [],
    Yaku.NoHonorTiles: [],
    Yaku.EdgeWait: [],
    Yaku.ClosedWait: [],
    Yaku.SingleWait: [],
    Yaku.SelfDrawn: [],
}
