from app.score_calculator.block.block import Block
from app.score_calculator.enums.enums import Yaku


def has_opened_blocks(blocks: list[Block]) -> bool:
    return any(block.is_opened for block in blocks)


excluded_yakus: dict[Yaku, list[Yaku]] = {
    Yaku.BigFourWinds: [
        Yaku.BigThreeWinds,
        Yaku.AllPungs,
        Yaku.PrevalentWind,
        Yaku.SeatWind,
        Yaku.PungOfTerminalsOrHonors,
    ],
    Yaku.BigThreeDragons: [Yaku.TwoDragonsPungs, Yaku.DragonPung],
    Yaku.NineGates: [
        Yaku.FullFlush,
        Yaku.ConcealedHand,
        Yaku.PungOfTerminalsOrHonors,
        Yaku.HalfFlush,
        Yaku.NoHonorTiles,
    ],
    Yaku.FourKongs: [
        Yaku.SingleWait,
        Yaku.AllPungs,
        Yaku.MeldedKong,
        Yaku.ConcealedKong,
        Yaku.TwoMeldedKongs,
        Yaku.TwoConcealedKongs,
        Yaku.ThreeKongs,
    ],
    Yaku.SevenShiftedPairs: [
        Yaku.FullFlush,
        Yaku.ConcealedHand,
        Yaku.SingleWait,
        Yaku.HalfFlush,
        Yaku.SevenPairs,
        Yaku.OneVoidedSuit,
        Yaku.NoHonorTiles,
    ],
    Yaku.AllGreen: [],
    Yaku.ThirteenOrphans: [
        Yaku.AllTypes,
        Yaku.ConcealedHand,
        Yaku.SingleWait,
        Yaku.AllTerminalsAndHonors,
    ],
    Yaku.AllTerminals: [
        Yaku.AllPungs,
        Yaku.OutsideHand,
        Yaku.PungOfTerminalsOrHonors,
        Yaku.NoHonorTiles,
        Yaku.AllTerminalsAndHonors,
    ],
    Yaku.LittleFourWinds: [
        Yaku.BigThreeWinds,
    ],  # Yaku.PungOfTerminalsOrHonors by used block flag
    Yaku.LittleThreeDragons: [Yaku.TwoDragonsPungs, Yaku.DragonPung],
    Yaku.AllHonors: [
        Yaku.AllPungs,
        Yaku.OutsideHand,
        Yaku.PungOfTerminalsOrHonors,
        Yaku.AllTerminalsAndHonors,
    ],
    Yaku.FourConcealedPungs: [
        Yaku.ThreeConcealedPungs,
        Yaku.TwoConcealedPungs,
        Yaku.AllPungs,
        Yaku.ConcealedHand,
    ],
    Yaku.PureTerminalChows: [
        Yaku.SevenPairs,
        Yaku.FullFlush,
        Yaku.AllChows,
        Yaku.NoHonorTiles,
        Yaku.PureDoubleChow,
        Yaku.TwoTerminalChows,
        Yaku.HalfFlush,
        Yaku.OneVoidedSuit,
    ],
    Yaku.QuadrupleChow: [Yaku.PureShiftedPungs, Yaku.TileHog, Yaku.PureDoubleChow],
    Yaku.FourPureShiftedPungs: [Yaku.PureTripleChow, Yaku.AllPungs],
    Yaku.FourPureShiftedChows: [Yaku.ShortStraight, Yaku.TwoTerminalChows],
    Yaku.ThreeKongs: [
        Yaku.MeldedKong,
        Yaku.ConcealedKong,
        Yaku.TwoMeldedKongs,
        Yaku.TwoConcealedKongs,
        Yaku.ThreeKongs,
    ],
    Yaku.AllTerminalsAndHonors: [
        Yaku.AllPungs,
        Yaku.OutsideHand,
        Yaku.PungOfTerminalsOrHonors,
    ],
    Yaku.SevenPairs: [Yaku.ConcealedHand, Yaku.SingleWait],
    Yaku.GreaterHonorsAndKnittedTiles: [
        Yaku.AllTypes,
        Yaku.ConcealedHand,
        Yaku.LesserHonorsAndKnittedTiles,
    ],
    Yaku.AllEvenPungs: [Yaku.AllPungs, Yaku.AllSimples, Yaku.NoHonorTiles],
    Yaku.FullFlush: [Yaku.NoHonorTiles, Yaku.OneVoidedSuit, Yaku.HalfFlush],
    Yaku.PureTripleChow: [Yaku.PureShiftedPungs, Yaku.PureDoubleChow],
    Yaku.PureShiftedPungs: [Yaku.PureTripleChow],
    Yaku.UpperTiles: [Yaku.NoHonorTiles, Yaku.UpperFour],
    Yaku.MiddleTiles: [Yaku.NoHonorTiles, Yaku.AllSimples],
    Yaku.LowerTiles: [Yaku.NoHonorTiles, Yaku.LowerFour],
    Yaku.PureStraight: [],
    Yaku.ThreeSuitedTerminalChows: [
        Yaku.AllChows,
        Yaku.NoHonorTiles,
        Yaku.MixedDoubleChow,
        Yaku.TwoTerminalChows,
    ],
    Yaku.PureShiftedChows: [],
    Yaku.AllFives: [Yaku.AllSimples, Yaku.NoHonorTiles],
    Yaku.TriplePung: [Yaku.DoublePung],
    Yaku.ThreeConcealedPungs: [Yaku.TwoConcealedPungs],
    Yaku.LesserHonorsAndKnittedTiles: [Yaku.AllTypes, Yaku.ConcealedHand],
    Yaku.KnittedStraight: [],
    Yaku.UpperFour: [Yaku.NoHonorTiles],
    Yaku.LowerFour: [Yaku.NoHonorTiles],
    Yaku.BigThreeWinds: [],  # Yaku.PungOfTerminals~ removed by used block flag
    Yaku.MixedStraight: [],
    Yaku.ReversibleTiles: [Yaku.OneVoidedSuit],
    Yaku.MixedTripleChow: [],
    Yaku.MixedShiftedPungs: [],
    Yaku.ChickenHand: [],
    Yaku.LastTileDraw: [Yaku.SelfDrawn],
    Yaku.LastTileClaim: [],
    Yaku.OutWithReplacementTile: [Yaku.SelfDrawn],
    Yaku.RobbingTheKong: [Yaku.LastTile],
    Yaku.TwoConcealedKongs: [
        Yaku.TwoMeldedKongs,
        Yaku.ConcealedKong,
        Yaku.TwoConcealedPungs,
    ],
    Yaku.AllPungs: [],
    Yaku.HalfFlush: [Yaku.OneVoidedSuit],
    Yaku.MixedShiftedChows: [],
    Yaku.AllTypes: [],
    Yaku.MeldedHand: [Yaku.SingleWait],
    Yaku.TwoDragonsPungs: [Yaku.DragonPung],
    Yaku.OutsideHand: [],
    Yaku.FullyConcealedHand: [Yaku.SelfDrawn],
    Yaku.TwoMeldedKongs: [Yaku.MeldedKong],
    Yaku.LastTile: [],
    Yaku.DragonPung: [],
    Yaku.PrevalentWind: [],
    Yaku.SeatWind: [],
    Yaku.ConcealedHand: [],
    Yaku.AllChows: [Yaku.NoHonorTiles],
    Yaku.TileHog: [],  # if (AllGreen or AllTerminals) and SevenPairs: must be removed
    Yaku.DoublePung: [],
    Yaku.TwoConcealedPungs: [],
    Yaku.ConcealedKong: [],
    Yaku.AllSimples: [Yaku.NoHonorTiles],
    Yaku.PureDoubleChow: [],
    Yaku.MixedDoubleChow: [],
    Yaku.ShortStraight: [],
    Yaku.TwoTerminalChows: [],
    Yaku.PungOfTerminalsOrHonors: [],
    Yaku.MeldedKong: [],
    Yaku.OneVoidedSuit: [],
    Yaku.NoHonorTiles: [],
    Yaku.EdgeWait: [],
    Yaku.ClosedWait: [],
    Yaku.SingleWait: [],
    Yaku.SelfDrawn: [],
}
